"""Launch file for displaying the "sample_rover" robot in RViz2.

Auto-generated by Fusion2ROS (fusion_addin/generators/package.py).
Regenerate from Fusion rather than editing by hand.
"""

from launch import LaunchDescription
from launch.substitutions import Command, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare

PACKAGE_NAME = "sample_rover"
URDF_XACRO_FILE = "sample_rover.urdf.xacro"
RVIZ_CONFIG_FILE = "sample_rover.rviz"


def generate_launch_description():
    pkg_share = FindPackageShare(PACKAGE_NAME)

    urdf_xacro_path = PathJoinSubstitution([pkg_share, "urdf", URDF_XACRO_FILE])
    rviz_config_path = PathJoinSubstitution([pkg_share, "rviz", RVIZ_CONFIG_FILE])

    # Processed via the `xacro` command-line filter at launch time rather
    # than the `xacro` Python module, so this launch file has no import-time
    # dependency on xacro being importable in the launching interpreter.
    robot_description = {
        "robot_description": Command(["xacro ", urdf_xacro_path])
    }

    robot_state_publisher_node = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        name="robot_state_publisher",
        output="screen",
        parameters=[robot_description],
    )

    joint_state_publisher_gui_node = Node(
        package="joint_state_publisher_gui",
        executable="joint_state_publisher_gui",
        name="joint_state_publisher_gui",
        output="screen",
    )

    rviz_node = Node(
        package="rviz2",
        executable="rviz2",
        name="rviz2",
        output="screen",
        arguments=["-d", rviz_config_path],
    )

    return LaunchDescription([
        robot_state_publisher_node,
        joint_state_publisher_gui_node,
        rviz_node,
    ])
