"""Gazebo Sim (gz-sim) spawn launch file for the "sample_rover" robot.

Auto-generated by Fusion2ROS (fusion_addin/generators/gazebo.py).
Regenerate rather than editing by hand.

Starts gz-sim (via ros_gz_sim's gz_sim.launch.py) against this package's
worlds/empty.sdf, publishes /robot_description via
robot_state_publisher (xacro-processed at launch time), and spawns the robot
into the running simulation from that live topic using ros_gz_sim's `create`
node -- see generate_spawn_launch's docstring in
fusion_addin/generators/gazebo.py for exactly how each of those names was
confirmed real on this machine's ROS 2 "lyrical" / gz-sim 10.4.0 install.
"""

from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command, PathJoinSubstitution, TextSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare

PACKAGE_NAME = "sample_rover"
XACRO_FILE = "sample_rover.urdf.xacro"
WORLD_FILE = "empty.sdf"
ENTITY_NAME = "sample_rover"


def generate_launch_description():
    pkg_share = FindPackageShare(PACKAGE_NAME)
    ros_gz_sim_share = FindPackageShare("ros_gz_sim")

    xacro_path = PathJoinSubstitution([pkg_share, "urdf", XACRO_FILE])
    world_path = PathJoinSubstitution([pkg_share, "worlds", WORLD_FILE])
    gz_sim_launch_path = PathJoinSubstitution([ros_gz_sim_share, "launch", "gz_sim.launch.py"])

    # Processed via the `xacro` command-line filter at launch time rather
    # than the `xacro` Python module, so this launch file has no import-time
    # dependency on xacro being importable in the launching interpreter --
    # same convention as this package's display.launch.py.
    robot_description = {
        "robot_description": Command(["xacro ", xacro_path])
    }

    gz_sim = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(gz_sim_launch_path),
        launch_arguments={"gz_args": [TextSubstitution(text="-r "), world_path]}.items(),
    )

    robot_state_publisher_node = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        name="robot_state_publisher",
        output="screen",
        parameters=[robot_description],
    )

    spawn_node = Node(
        package="ros_gz_sim",
        executable="create",
        name="spawn_sample_rover",
        output="screen",
        parameters=[{
            "name": ENTITY_NAME,
            "topic": "/robot_description",
            "allow_renaming": True,
        }],
    )

    return LaunchDescription([
        gz_sim,
        robot_state_publisher_node,
        spawn_node,
    ])
