"""Nav2 bringup launch file for the "sample_rover" robot.

Auto-generated by Fusion2ROS (fusion_addin/generators/nav2.py). Includes
nav2_bringup's own bringup_launch.py -- the standard, documented way to start
Nav2's full lifecycle-managed stack -- rather than hand-rolling individual
lifecycle nodes here.

Regenerate from Fusion rather than editing by hand.
"""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.substitutions import FindPackageShare

PACKAGE_NAME = "sample_rover"


def generate_launch_description():
    pkg_share = FindPackageShare(PACKAGE_NAME)
    nav2_bringup_share = FindPackageShare("nav2_bringup")

    default_params_file = PathJoinSubstitution([pkg_share, "params", "nav2_params.yaml"])
    default_map_file = PathJoinSubstitution([pkg_share, "maps", "map.yaml"])
    bringup_launch_file = PathJoinSubstitution([nav2_bringup_share, "launch", "bringup_launch.py"])

    namespace_arg = DeclareLaunchArgument(
        "namespace", default_value="", description="Top-level namespace"
    )
    use_sim_time_arg = DeclareLaunchArgument(
        "use_sim_time", default_value="false", description="Use simulation (Gazebo) clock if true"
    )
    map_arg = DeclareLaunchArgument(
        "map", default_value=default_map_file, description="Full path to the map yaml file to load"
    )
    params_file_arg = DeclareLaunchArgument(
        "params_file", default_value=default_params_file, description="Full path to the Nav2 parameters file"
    )
    autostart_arg = DeclareLaunchArgument(
        "autostart", default_value="true", description="Automatically start the Nav2 lifecycle nodes"
    )

    nav2_bringup = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(bringup_launch_file),
        launch_arguments={
            "namespace": LaunchConfiguration("namespace"),
            "use_sim_time": LaunchConfiguration("use_sim_time"),
            "map": LaunchConfiguration("map"),
            "params_file": LaunchConfiguration("params_file"),
            "autostart": LaunchConfiguration("autostart"),
        }.items(),
    )

    return LaunchDescription(
        [
            namespace_arg,
            use_sim_time_arg,
            map_arg,
            params_file_arg,
            autostart_arg,
            nav2_bringup,
        ]
    )
