"""Control launch file for the "sample_arm" robot.

Auto-generated by Fusion2ROS (fusion_addin/generators/ros2_control.py).
Regenerate rather than editing by hand.

Starts robot_state_publisher (publishes /robot_description -- ros2_control_node
subscribes to it rather than only reading it as a parameter) and
controller_manager/ros2_control_node (parameterized by robot_description +
controllers.yaml), then spawns joint_state_broadcaster plus joint_trajectory_controller
via controller_manager's spawner executable.
"""

from launch import LaunchDescription
from launch.substitutions import Command, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare

PACKAGE_NAME = "sample_arm"
URDF_XACRO_FILE = "sample_arm.urdf.xacro"
CONTROLLERS_YAML_FILE = "controllers.yaml"

SECOND_CONTROLLER = "joint_trajectory_controller"


def generate_launch_description():
    pkg_share = FindPackageShare(PACKAGE_NAME)

    urdf_xacro_path = PathJoinSubstitution([pkg_share, "urdf", URDF_XACRO_FILE])
    controllers_yaml_path = PathJoinSubstitution([pkg_share, "config", CONTROLLERS_YAML_FILE])

    # Processed via the `xacro` command-line filter at launch time rather
    # than the `xacro` Python module, so this launch file has no import-time
    # dependency on xacro being importable in the launching interpreter.
    robot_description = {
        "robot_description": Command(["xacro ", urdf_xacro_path])
    }

    robot_state_publisher_node = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        name="robot_state_publisher",
        output="screen",
        parameters=[robot_description],
    )

    control_node = Node(
        package="controller_manager",
        executable="ros2_control_node",
        name="controller_manager",
        parameters=[robot_description, controllers_yaml_path],
        output="both",
    )

    joint_state_broadcaster_spawner = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["joint_state_broadcaster", "--param-file", controllers_yaml_path],
        output="screen",
    )

    second_controller_spawner = Node(
        package="controller_manager",
        executable="spawner",
        arguments=[SECOND_CONTROLLER, "--param-file", controllers_yaml_path],
        output="screen",
    )

    return LaunchDescription([
        robot_state_publisher_node,
        control_node,
        joint_state_broadcaster_spawner,
        second_controller_spawner,
    ])
