"""MoveIt 2 demo launch file for "sample_arm" (planning group "arm").

Auto-generated by fusion_addin/generators/moveit.py's generate_moveit_demo_launch.
Regenerate rather than editing by hand.

Hand-rolled rather than using moveit_configs_utils.MoveItConfigsBuilder -- MoveIt 2
was not installed in the environment this was generated against, so that helper's
API/availability could not be verified. See generate_moveit_demo_launch's docstring
in fusion_addin/generators/moveit.py for the full list of simplifications relative
to a real moveit_setup_assistant-generated package (no tuned OMPL pipeline params,
no pre-built MotionPlanning rviz display, etc).

Assumes the standard package layout this generator was built against:
  "sample_arm"        share dir: urdf/sample_arm.urdf.xacro
  "sample_arm" share dir: config/sample_arm.srdf, config/kinematics.yaml,
                                          config/joint_limits.yaml,
                                          config/moveit_controllers.yaml
Assembling that package tree from these generated file contents is
fusion_addin/generators/package.py's job, not this launch file's.
"""

import yaml
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.substitutions import Command, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare

DESCRIPTION_PACKAGE = "sample_arm"
MOVEIT_CONFIG_PACKAGE = "sample_arm"
URDF_XACRO_FILE = "sample_arm.urdf.xacro"
SRDF_FILE = "sample_arm.srdf"
PLANNING_GROUP = "arm"


def _load_file(package_name, relative_path):
    path = PathJoinSubstitution([FindPackageShare(package_name), relative_path])
    # Resolved eagerly (not as a launch Substitution) because move_group's
    # robot_description_semantic parameter must be a plain string, not a
    # Substitution object -- this mirrors the common MoveIt tutorial pattern.
    absolute_path = f"{get_package_share_directory(package_name)}/{relative_path}"
    with open(absolute_path, "r") as f:
        return f.read()


def _load_yaml(package_name, relative_path):
    absolute_path = f"{get_package_share_directory(package_name)}/{relative_path}"
    with open(absolute_path, "r") as f:
        return yaml.safe_load(f)


def generate_launch_description():
    urdf_xacro_path = PathJoinSubstitution(
        [FindPackageShare(DESCRIPTION_PACKAGE), "urdf", URDF_XACRO_FILE]
    )
    # Processed via the `xacro` command-line filter at launch time, same
    # convention fusion_addin/generators/package.py's display.launch.py uses --
    # no import-time dependency on the `xacro` Python module.
    robot_description = {"robot_description": Command(["xacro ", urdf_xacro_path])}

    robot_description_semantic = {
        "robot_description_semantic": _load_file(MOVEIT_CONFIG_PACKAGE, f"config/{SRDF_FILE}")
    }

    kinematics_yaml = _load_yaml(MOVEIT_CONFIG_PACKAGE, "config/kinematics.yaml")
    robot_description_kinematics = {"robot_description_kinematics": kinematics_yaml}

    joint_limits_yaml = _load_yaml(MOVEIT_CONFIG_PACKAGE, "config/joint_limits.yaml")
    robot_description_planning = {"robot_description_planning": joint_limits_yaml}

    controllers_yaml = _load_yaml(MOVEIT_CONFIG_PACKAGE, "config/moveit_controllers.yaml")
    moveit_controllers = {
        "moveit_simple_controller_manager": controllers_yaml["moveit_simple_controller_manager"],
        "moveit_controller_manager": "moveit_simple_controller_manager/MoveItSimpleControllerManager",
    }

    # move_group throws std::runtime_error and terminates immediately with
    # no planning pipeline registered at all -- confirmed for real, not a
    # tunable simplification. See generate_ompl_planning_yaml's docstring in
    # fusion_addin/generators/moveit.py.
    ompl_yaml = _load_yaml(MOVEIT_CONFIG_PACKAGE, "config/ompl_planning.yaml")
    planning_pipeline_config = {
        "planning_pipelines": ["ompl"],
        "default_planning_pipeline": "ompl",
        "ompl": ompl_yaml,
    }

    move_group_node = Node(
        package="moveit_ros_move_group",
        executable="move_group",
        output="screen",
        parameters=[
            robot_description,
            robot_description_semantic,
            robot_description_kinematics,
            robot_description_planning,
            moveit_controllers,
            planning_pipeline_config,
            {"allow_trajectory_execution": True},
            {"publish_monitored_planning_scene": True},
        ],
    )

    rviz_node = Node(
        package="rviz2",
        executable="rviz2",
        name="rviz2",
        output="screen",
        parameters=[
            robot_description,
            robot_description_semantic,
            robot_description_kinematics,
        ],
    )

    return LaunchDescription([move_group_node, rviz_node])
