"""RobotModel + a set of already-generated launch files -> one combined
"bringup" launch that starts all of them together.

Real gap this closes: `nav2_bringup.launch.py` and `moveit_demo.launch.py`
(generators/nav2.py, generators/moveit.py) each deliberately do NOT start
`robot_state_publisher` themselves -- they assume something else already
provides `/robot_description`/TF (confirmed by reading both generators: no
`robot_state_publisher` Node in either). `display.launch.py`,
`gazebo.launch.py`, and `control.launch.py` (generators/package.py,
gazebo.py, ros2_control.py respectively) each independently DO start their
own `robot_state_publisher` -- so before this module, a user who checked
both "Gazebo" and "Nav2" had no single launch file that actually worked:
running `nav2_bringup.launch.py` alone has nothing to navigate (no sim, no
robot_description), and running it alongside `gazebo.launch.py` required
knowing to start both by hand in two terminals.

`generate_bringup_launch` composes exactly ONE "base" launch (the one thing
that must start `robot_state_publisher`, chosen by priority: Gazebo (has a
sim + robot_description) > ros2_control (mock/real hardware +
robot_description) > display (pure visualization fallback, always
available) -- picking more than one base would start robot_state_publisher
twice, which is redundant, not merely wasteful: two nodes publishing the
same topic/TF race each other) plus any of the "stack" launches (Nav2,
MoveIt) that don't provide their own base.

Pure function of plain booleans -- no Fusion API, no filesystem, no
robot-specific data needed beyond `robot.name` (every include is by a fixed
package-relative launch file path). Safe to import/call from Fusion's
embedded interpreter, from plain WSL `python3`, or from CI with neither
installed, same constraint every other fusion_addin/generators/ module is
held to.
"""

from __future__ import annotations

from typing import Optional

from robot_model import Robot

__all__ = ["generate_bringup_launch"]

_BASE_LAUNCH_FILES = {
    "gazebo": "gazebo.launch.py",
    "ros2_control": "control.launch.py",
    "display": "display.launch.py",
}


def _choose_base(include_ros2_control: bool, include_gazebo: bool) -> str:
    if include_gazebo:
        return "gazebo"
    if include_ros2_control:
        return "ros2_control"
    return "display"


def generate_bringup_launch(
    robot: Robot,
    include_ros2_control: bool,
    include_gazebo: bool,
    include_moveit: bool,
    include_nav2: bool,
) -> Optional[str]:
    """Render a combined `bringup.launch.py`, or return `None` when there is
    nothing to combine (see module docstring: only Nav2/MoveIt need a
    launch file combined with something else at all -- display/gazebo/
    control alone are already complete, standalone-runnable launch files,
    so generating a redundant one-file "combination" of just one thing
    would only be confusing).

    Verification: this module's own docstring already establishes, by
    reading the real generator source, which of the five launch files this
    project generates start their own `robot_state_publisher` and which
    don't -- the base-vs-stack split follows directly from that, not
    guessed convention.
    """
    if not (include_moveit or include_nav2):
        return None

    base = _choose_base(include_ros2_control, include_gazebo)
    included = [base]
    if include_nav2:
        included.append("nav2")
    if include_moveit:
        included.append("moveit")

    base_file = _BASE_LAUNCH_FILES[base]
    include_lines = [f'PathJoinSubstitution([pkg_share, "launch", "{base_file}"])']
    comment_lines = [f"- {base_file} (base: provides /robot_description and TF)"]
    if include_nav2:
        include_lines.append('PathJoinSubstitution([pkg_share, "launch", "nav2_bringup.launch.py"])')
        comment_lines.append("- nav2_bringup.launch.py")
    if include_moveit:
        include_lines.append('PathJoinSubstitution([pkg_share, "launch", "moveit_demo.launch.py"])')
        comment_lines.append("- moveit_demo.launch.py")

    include_actions = "\n".join(
        f"""
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource({path}),
        ),"""
        for path in include_lines
    )

    return f'''"""Combined bringup launch for the "{robot.name}" robot.

Auto-generated by Fusion2ROS (fusion_addin/generators/bringup.py).
Regenerate rather than editing by hand.

Starts, together, in this order:
{chr(10).join(comment_lines)}

See generate_bringup_launch's docstring in
fusion_addin/generators/bringup.py for why exactly one of
display/gazebo/control.launch.py is the "base" (the only one that should
start robot_state_publisher) and nav2_bringup.launch.py/moveit_demo.launch.py
are layered on top of it, never used as a base themselves.
"""

from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import PathJoinSubstitution
from launch_ros.substitutions import FindPackageShare

PACKAGE_NAME = "{robot.name}"


def generate_launch_description():
    pkg_share = FindPackageShare(PACKAGE_NAME)

    return LaunchDescription([{include_actions}
    ])
'''
