"""RobotModel + URDF + meshes -> a complete, portable ROS 2 package tree.

This module writes a ROS 2 (ament_cmake) package to disk given:

- a validated ``robot_model.Robot`` (used only for its name and root link —
  the actual URDF authoring is done by ``fusion_addin/generators/urdf.py``),
- the already-generated URDF/Xacro text,
- a mapping of mesh files to embed,

and produces ``<output_dir>/<robot.name>/`` containing ``package.xml``,
``CMakeLists.txt``, ``urdf/``, ``meshes/``, ``launch/`` and ``rviz/``.

Pure stdlib. No Fusion API calls, no ROS/rclpy imports — this must be
importable and testable under plain WSL/CI ``python3`` just like
``robot_model``, even though it lives under ``fusion_addin/`` and is only
*run* from inside Fusion's embedded interpreter in production.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Dict, Optional, Union

from robot_model import Robot

MeshSource = Union[bytes, Path]
FileContent = Union[str, bytes]


def generate_package(
    robot: Robot,
    urdf_xacro: str,
    mesh_files: Dict[str, MeshSource],
    output_dir: Path,
    extra_files: Optional[Dict[str, FileContent]] = None,
) -> Path:
    """Write a complete ROS 2 package tree for ``robot`` under ``output_dir``.

    Returns the path to the generated package directory
    (``output_dir / robot.name``).

    Idempotent: if the target package directory already exists, it is
    removed and rebuilt from scratch so no file from a previous generation
    (e.g. a mesh that is no longer referenced) lingers.

    ``extra_files`` writes additional package-relative files (e.g.
    ``"config/controllers.yaml"``, ``"launch/control.launch.py"``,
    ``"config/<robot>.srdf"``) beyond the standard urdf/meshes/launch/rviz
    set -- str values are written as text, bytes as binary. This is the
    integration point the ros2_control/Gazebo/MoveIt/Nav2 generators plug
    into: each of those produces plain XML/YAML/launch text, and this is
    where it actually lands on disk as part of one coherent package.
    """
    output_dir = Path(output_dir)
    pkg_dir = output_dir / robot.name

    if pkg_dir.exists():
        shutil.rmtree(pkg_dir)

    urdf_dir = pkg_dir / "urdf"
    meshes_dir = pkg_dir / "meshes"
    launch_dir = pkg_dir / "launch"
    rviz_dir = pkg_dir / "rviz"
    config_dir = pkg_dir / "config"
    for d in (pkg_dir, urdf_dir, meshes_dir, launch_dir, rviz_dir, config_dir):
        d.mkdir(parents=True, exist_ok=True)

    _write_package_xml(robot, pkg_dir)
    _write_urdf_xacro(robot, urdf_dir, urdf_xacro)
    _write_meshes(mesh_files, meshes_dir)
    _write_launch(robot, launch_dir)
    _write_rviz(robot, rviz_dir)
    _write_extra_files(extra_files or {}, pkg_dir)

    # Written last: extra_files can introduce entirely new top-level dirs
    # (e.g. gazebo.py's "worlds/") beyond the fixed urdf/meshes/launch/rviz/
    # config set -- discovering what's actually on disk here, rather than
    # hardcoding a directory list, is what makes CMakeLists actually install
    # them. (A real bug this exact gap caused: a generated worlds/empty.sdf
    # sat in the package but was never installed, so `gz sim` reported
    # "Unable to find or download file ... worlds/empty.sdf" at launch even
    # though colcon build had reported success.)
    install_dirs = sorted(p.name for p in pkg_dir.iterdir() if p.is_dir())
    _write_cmakelists(robot, pkg_dir, install_dirs)

    return pkg_dir


def _write_extra_files(extra_files: Dict[str, FileContent], pkg_dir: Path) -> None:
    for rel_path, content in extra_files.items():
        dest = pkg_dir / rel_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(content, str):
            dest.write_text(content, encoding="utf-8")
        elif isinstance(content, (bytes, bytearray)):
            dest.write_bytes(bytes(content))
        else:
            raise TypeError(f"extra_files[{rel_path!r}] must be str or bytes, got {type(content).__name__}")


def _write_package_xml(robot: Robot, pkg_dir: Path) -> None:
    meta = robot.metadata or {}
    version = meta.get("version", "0.0.1")
    description = meta.get(
        "description", f"ROS 2 package for the {robot.name} robot, generated by Fusion2ROS."
    )
    maintainer_name = meta.get("maintainer_name", "TODO")
    maintainer_email = meta.get("maintainer_email", "TODO@TODO.TODO")
    license_name = meta.get("license", "TODO: License declaration")

    depends = [
        "urdf",
        "xacro",
        "robot_state_publisher",
        "joint_state_publisher",
        "joint_state_publisher_gui",
        "rviz2",
        "launch",
        "launch_ros",
    ]
    depend_lines = "\n".join(f"  <depend>{d}</depend>" for d in depends)

    content = f"""<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>{robot.name}</name>
  <version>{version}</version>
  <description>{description}</description>
  <maintainer email="{maintainer_email}">{maintainer_name}</maintainer>
  <license>{license_name}</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

{depend_lines}

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
"""
    (pkg_dir / "package.xml").write_text(content, encoding="utf-8")


def _write_cmakelists(robot: Robot, pkg_dir: Path, install_dirs) -> None:
    dir_lines = "\n".join(f"    {d}" for d in install_dirs)
    content = f"""cmake_minimum_required(VERSION 3.10)
project({robot.name})

find_package(ament_cmake REQUIRED)

install(
  DIRECTORY
{dir_lines}
  DESTINATION share/${{PROJECT_NAME}}
)

ament_package()
"""
    (pkg_dir / "CMakeLists.txt").write_text(content, encoding="utf-8")


def _write_urdf_xacro(robot: Robot, urdf_dir: Path, urdf_xacro: str) -> None:
    (urdf_dir / f"{robot.name}.urdf.xacro").write_text(urdf_xacro, encoding="utf-8")


def _write_meshes(mesh_files: Dict[str, MeshSource], meshes_dir: Path) -> None:
    for rel_name, source in mesh_files.items():
        dest = meshes_dir / rel_name
        dest.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(source, Path):
            shutil.copyfile(source, dest)
        elif isinstance(source, (bytes, bytearray)):
            dest.write_bytes(bytes(source))
        else:
            raise TypeError(
                f"mesh_files[{rel_name!r}] must be bytes or a pathlib.Path, got {type(source).__name__}"
            )


def _write_launch(robot: Robot, launch_dir: Path) -> None:
    content = f'''"""Launch file for displaying the "{robot.name}" robot in RViz2.

Auto-generated by Fusion2ROS (fusion_addin/generators/package.py).
Regenerate from Fusion rather than editing by hand.
"""

from launch import LaunchDescription
from launch.substitutions import Command, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare

PACKAGE_NAME = "{robot.name}"
URDF_XACRO_FILE = "{robot.name}.urdf.xacro"
RVIZ_CONFIG_FILE = "{robot.name}.rviz"


def generate_launch_description():
    pkg_share = FindPackageShare(PACKAGE_NAME)

    urdf_xacro_path = PathJoinSubstitution([pkg_share, "urdf", URDF_XACRO_FILE])
    rviz_config_path = PathJoinSubstitution([pkg_share, "rviz", RVIZ_CONFIG_FILE])

    # Processed via the `xacro` command-line filter at launch time rather
    # than the `xacro` Python module, so this launch file has no import-time
    # dependency on xacro being importable in the launching interpreter.
    robot_description = {{
        "robot_description": Command(["xacro ", urdf_xacro_path])
    }}

    robot_state_publisher_node = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        name="robot_state_publisher",
        output="screen",
        parameters=[robot_description],
    )

    joint_state_publisher_gui_node = Node(
        package="joint_state_publisher_gui",
        executable="joint_state_publisher_gui",
        name="joint_state_publisher_gui",
        output="screen",
    )

    rviz_node = Node(
        package="rviz2",
        executable="rviz2",
        name="rviz2",
        output="screen",
        arguments=["-d", rviz_config_path],
    )

    return LaunchDescription([
        robot_state_publisher_node,
        joint_state_publisher_gui_node,
        rviz_node,
    ])
'''
    (launch_dir / "display.launch.py").write_text(content, encoding="utf-8")


def _write_rviz(robot: Robot, rviz_dir: Path) -> None:
    root = robot.root_link()
    fixed_frame = root.name if root is not None else "base_link"

    content = f"""Panels:
  - Class: rviz_common/Displays
    Name: Displays
Visualization Manager:
  Class: ""
  Displays:
    - Alpha: 1
      Class: rviz_default_plugins/RobotModel
      Description Topic:
        Depth: 5
        Durability Policy: Volatile
        History Policy: Keep Last
        Reliability Policy: Reliable
        Value: /robot_description
      Enabled: true
      Name: RobotModel
      TF Prefix: ""
      Update Interval: 0
      Value: true
      Visual Enabled: true
    - Class: rviz_default_plugins/TF
      Enabled: true
      Name: TF
      Value: true
  Enabled: true
  Global Options:
    Background Color: 48; 48; 48
    Fixed Frame: {fixed_frame}
    Frame Rate: 30
  Name: root
  Tools:
    - Class: rviz_default_plugins/Interact
      Hide Inactive Objects: true
    - Class: rviz_default_plugins/MoveCamera
    - Class: rviz_default_plugins/Select
  Value: true
  Views:
    Current:
      Class: rviz_default_plugins/Orbit
      Distance: 3
      Focal Point:
        X: 0
        Y: 0
        Z: 0
      Name: Current View
      Pitch: 0.5
      Yaw: 0.5
    Saved: ~
Window Geometry:
  Height: 800
  Width: 1200
  X: 0
  Y: 0
"""
    (rviz_dir / f"{robot.name}.rviz").write_text(content, encoding="utf-8")
